# Generated by Django 4.2.6 on 2024-03-23 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentSemester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SM.semester')),
            ],
        ),
    ]
