# Generated by Django 4.2.7 on 2024-04-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='scores',
            field=models.FloatField(blank=True, null=True, verbose_name=models.FloatField()),
        ),
    ]
