# Generated by Django 4.2.6 on 2024-04-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SM', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroomsubject',
            name='subject',
            field=models.ManyToManyField(blank=True, related_name='classroom_subjects', to='SM.subject'),
        ),
    ]
