# Generated by Django 4.2.6 on 2024-03-23 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SM', '0002_currentsemester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='semester',
        ),
        migrations.DeleteModel(
            name='CurrentSemester',
        ),
    ]
