# Generated by Django 4.2.6 on 2024-03-25 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SM', '0003_remove_mark_semester_delete_currentsemester'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TableSchedule',
            new_name='Schedule',
        ),
    ]
