# Generated by Django 4.2.6 on 2024-03-28 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SM', '0004_rename_tableschedule_schedule'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('classroom', 'dayofweek', 'period')},
        ),
    ]
