# Generated by Django 4.2.6 on 2024-04-01 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SM', '0006_alter_schedule_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroomsubject',
            name='subject',
            field=models.ManyToManyField(blank=True, related_name='subjects', to='SM.subject'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='SM.student'),
        ),
    ]
