# Generated by Django 4.2.6 on 2024-03-28 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SM', '0004_rename_tableschedule_schedule'),
        ('CM', '0003_alter_lessons_grade'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('classroom', 'row', 'column')},
        ),
    ]
